version: '3'

services:
  db:
    image: percona:8
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "BzbPSQdNBMoU"
      MYSQL_DATABASE: "db_app"
      MYSQL_USER: "dbadmin"
      MYSQL_PASSWORD: "yBbAI5uvlpWV"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

  build_app:
    build:
      context: build
      dockerfile: Dockerfile
    volumes:
      - app:/opt/app/target

  webapp:
    build:
      context: prod
      dockerfile: Dockerfile
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-1.7-openjdk/jre/bin
      - JRE_HOME=/usr/lib/jvm/java-1.7-openjdk/jre
    ports:
      - "80:8080"
    volumes:
      - app:/opt/apache-tomcat-6.0.0/webapps
    depends_on:
      - build_app
      - db

volumes:
  app:
  mysql:
